# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bdomansk <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/04/23 11:55:49 by bdomansk          #+#    #+#              #
#    Updated: 2018/04/23 11:55:51 by bdomansk         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ../corewar
LIB = ../libft/libft.a
LIBDIR = ../libft
FLAGS = -Wall -Wextra -Werror -g
COREWAR_SRC = main.c init_info.c put_manual.c parse_arguments.c reverse.c \
	print_winner.c is_natural.c check_bot.c error.c fill_map.c draw_map.c \
	new_carriage.c visualization_init.c check_key.c define_bots_id.c  \
	draw_info_table.c npause.c introducing_contestants.c sdl_mixer_init.c \
	print_map.c close_visulization.c perform_carriages.c check_carriages.c \
	ft_live.c 
COREWAR_OBJ = $(COREWAR_SRC:.c=.o)
COREWAR_HEADER = ../includes/corewar.h ../includes/op_corewar.h
HEADER = -I ../includes
HEADER += -I ../frameworks/SDL2.framework/Headers/
HEADER += -I ../frameworks/SDL2_mixer.framework/Headers/ -F ../frameworks
FRAMEWORKS = -framework SDL2
FRAMEWORKS += -F  ../frameworks
FRAMEWORKS += -framework SDL2_mixer 
FRAMEWORKS += -rpath frameworks
DEL = /bin/rm -f

.PHONY : all clean n fclean re 

all : $(NAME)

$(NAME) : $(COREWAR_OBJ) $(LIB) 
	@echo "Compiling corewar"
	@gcc $(FLAGS) $(COREWAR_OBJ) -o $(NAME) -lncurses $(LIB) $(FRAMEWORKS)

$(COREWAR_OBJ): $(COREWAR_SRC) $(COREWAR_HEADER)
	@echo "Corewar objects creating"
	@gcc $(FLAGS) -c $(COREWAR_SRC) $(HEADER)


$(LIB) :
	@make -C $(LIBDIR)

clean:
	@$(DEL) $(COREWAR_OBJ)

n :
	@norminette $(COREWAR_SRC) 

fclean:
	@$(DEL) $(COREWAR_OBJ)
	@$(DEL) $(NAME)
	
re: fclean all